<?xml version="1.0" encoding="utf-8"?>
<mrng:Connections xmlns:mrng="http://mremoteng.org" Name="Connections" Export="false"
    EncryptionEngine="AES" BlockCipherMode="GCM" KdfIterations="1000" FullFileEncryption="false"
    Protected="XfqVzLoG5xgbOzHszR/I4QB8V/8/dTtenqwdUoyNXeBjfCSbwYNeRVmX+Sg48aRXeXdjgvlEdVifoIbMUTMG6rjy"
    ConfVersion="2.6">
    <Node Name="AWS" Type="Container" Expanded="true" Descr="" Icon="mRemoteNG" Panel="General"
        Id="faeeac76-a314-4780-b10b-c7c843459435" Username="${USERNAME}"
        Domain="${DOMAIN_NETBIOS_NAME}" Password=""
        Hostname="" Protocol="RDP" PuttySession="Default Settings" Port="3389"
        ConnectToConsole="false" UseCredSsp="true" RenderingEngine="IE"
        ICAEncryptionStrength="EncrBasic" RDPAuthenticationLevel="NoAuth"
        RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false" LoadBalanceInfo=""
        Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
        DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
        EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
        RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
        RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false" Connected="false"
        PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp="" VNCCompression="CompNone"
        VNCEncoding="EncHextile" VNCAuthMode="AuthVNC" VNCProxyType="ProxyNone" VNCProxyIP=""
        VNCProxyPort="0" VNCProxyUsername="" VNCProxyPassword="" VNCColors="ColNormal"
        VNCSmartSizeMode="SmartSAspect" VNCViewOnly="false" RDGatewayUsageMethod="Never"
        RDGatewayHostname="" RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername=""
        RDGatewayPassword="" RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
        InheritDescription="false" InheritDisplayThemes="false" InheritDisplayWallpaper="false"
        InheritEnableFontSmoothing="false" InheritEnableDesktopComposition="false"
        InheritDomain="false" InheritIcon="false" InheritPanel="false" InheritPassword="false"
        InheritPort="false" InheritProtocol="false" InheritPuttySession="false"
        InheritRedirectDiskDrives="false" InheritRedirectKeys="false" InheritRedirectPorts="false"
        InheritRedirectPrinters="false" InheritRedirectSmartCards="false"
        InheritRedirectSound="false" InheritSoundQuality="false" InheritResolution="false"
        InheritAutomaticResize="false" InheritUseConsoleSession="false" InheritUseCredSsp="false"
        InheritRenderingEngine="false" InheritUsername="false" InheritICAEncryptionStrength="false"
        InheritRDPAuthenticationLevel="false" InheritRDPMinutesToIdleTimeout="false"
        InheritRDPAlertIdleTimeout="false" InheritLoadBalanceInfo="false" InheritPreExtApp="false"
        InheritPostExtApp="false" InheritMacAddress="false" InheritUserField="false"
        InheritExtApp="false" InheritVNCCompression="false" InheritVNCEncoding="false"
        InheritVNCAuthMode="false" InheritVNCProxyType="false" InheritVNCProxyIP="false"
        InheritVNCProxyPort="false" InheritVNCProxyUsername="false" InheritVNCProxyPassword="false"
        InheritVNCColors="false" InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
        InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
        InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
        InheritRDGatewayPassword="false" InheritRDGatewayDomain="false">
        <Node Name="Main" Type="Container" Expanded="true" Descr="" Icon="mRemoteNG" Panel="General"
            Id="b79e3472-6d31-4889-92e7-e877c55b2e7b" Username="" Domain="" Password="" Hostname=""
            Protocol="RDP" PuttySession="Default Settings" Port="3389" ConnectToConsole="false"
            UseCredSsp="true" RenderingEngine="IE" ICAEncryptionStrength="EncrBasic"
            RDPAuthenticationLevel="NoAuth" RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false"
            LoadBalanceInfo="" Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
            DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
            EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
            RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
            RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false" Connected="false"
            PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp=""
            VNCCompression="CompNone" VNCEncoding="EncHextile" VNCAuthMode="AuthVNC"
            VNCProxyType="ProxyNone" VNCProxyIP="" VNCProxyPort="0" VNCProxyUsername=""
            VNCProxyPassword="" VNCColors="ColNormal" VNCSmartSizeMode="SmartSAspect"
            VNCViewOnly="false" RDGatewayUsageMethod="Never" RDGatewayHostname=""
            RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername="" RDGatewayPassword=""
            RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
            InheritDescription="false" InheritDisplayThemes="false" InheritDisplayWallpaper="false"
            InheritEnableFontSmoothing="false" InheritEnableDesktopComposition="false"
            InheritDomain="true" InheritIcon="false" InheritPanel="false" InheritPassword="true"
            InheritPort="false" InheritProtocol="false" InheritPuttySession="false"
            InheritRedirectDiskDrives="false" InheritRedirectKeys="false"
            InheritRedirectPorts="false" InheritRedirectPrinters="false"
            InheritRedirectSmartCards="false" InheritRedirectSound="false"
            InheritSoundQuality="false" InheritResolution="false" InheritAutomaticResize="false"
            InheritUseConsoleSession="false" InheritUseCredSsp="false"
            InheritRenderingEngine="false" InheritUsername="true"
            InheritICAEncryptionStrength="false" InheritRDPAuthenticationLevel="false"
            InheritRDPMinutesToIdleTimeout="false" InheritRDPAlertIdleTimeout="false"
            InheritLoadBalanceInfo="false" InheritPreExtApp="false" InheritPostExtApp="false"
            InheritMacAddress="false" InheritUserField="false" InheritExtApp="false"
            InheritVNCCompression="false" InheritVNCEncoding="false" InheritVNCAuthMode="false"
            InheritVNCProxyType="false" InheritVNCProxyIP="false" InheritVNCProxyPort="false"
            InheritVNCProxyUsername="false" InheritVNCProxyPassword="false" InheritVNCColors="false"
            InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
            InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
            InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
            InheritRDGatewayPassword="false" InheritRDGatewayDomain="false">
            <Node Name="Domain Controller" Type="Connection" Descr="" Icon="Windows" Panel="General"
                Id="54466acd-cdff-45d6-bc62-85d6a2995973" Username="" Domain="" Password=""
                Hostname="${DC01_PUBLIC_IP}" Protocol="RDP" PuttySession="Default Settings"
                Port="3389"
                ConnectToConsole="false" UseCredSsp="true" RenderingEngine="IE"
                ICAEncryptionStrength="EncrBasic" RDPAuthenticationLevel="NoAuth"
                RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false" LoadBalanceInfo=""
                Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
                DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
                EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
                RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
                RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false"
                Connected="false" PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp=""
                VNCCompression="CompNone" VNCEncoding="EncHextile" VNCAuthMode="AuthVNC"
                VNCProxyType="ProxyNone" VNCProxyIP="" VNCProxyPort="0" VNCProxyUsername=""
                VNCProxyPassword="" VNCColors="ColNormal" VNCSmartSizeMode="SmartSAspect"
                VNCViewOnly="false" RDGatewayUsageMethod="Never" RDGatewayHostname=""
                RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername="" RDGatewayPassword=""
                RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
                InheritDescription="false" InheritDisplayThemes="false"
                InheritDisplayWallpaper="false" InheritEnableFontSmoothing="false"
                InheritEnableDesktopComposition="false" InheritDomain="true" InheritIcon="false"
                InheritPanel="false" InheritPassword="true" InheritPort="false"
                InheritProtocol="false" InheritPuttySession="false"
                InheritRedirectDiskDrives="false" InheritRedirectKeys="false"
                InheritRedirectPorts="false" InheritRedirectPrinters="false"
                InheritRedirectSmartCards="false" InheritRedirectSound="false"
                InheritSoundQuality="false" InheritResolution="false" InheritAutomaticResize="false"
                InheritUseConsoleSession="false" InheritUseCredSsp="false"
                InheritRenderingEngine="false" InheritUsername="true"
                InheritICAEncryptionStrength="false" InheritRDPAuthenticationLevel="false"
                InheritRDPMinutesToIdleTimeout="false" InheritRDPAlertIdleTimeout="false"
                InheritLoadBalanceInfo="false" InheritPreExtApp="false" InheritPostExtApp="false"
                InheritMacAddress="false" InheritUserField="false" InheritExtApp="false"
                InheritVNCCompression="false" InheritVNCEncoding="false" InheritVNCAuthMode="false"
                InheritVNCProxyType="false" InheritVNCProxyIP="false" InheritVNCProxyPort="false"
                InheritVNCProxyUsername="false" InheritVNCProxyPassword="false"
                InheritVNCColors="false" InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
                InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
                InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
                InheritRDGatewayPassword="false" InheritRDGatewayDomain="false" />
            <Node Name="Cloud Connector" Type="Connection" Descr="" Icon="Windows" Panel="General"
                Id="49a0600a-2d4a-4f05-9c08-ef8c3d678ef9" Username="" Domain="" Password=""
                Hostname="${CC01_PUBLIC_IP}" Protocol="RDP" PuttySession="Default Settings"
                Port="3389"
                ConnectToConsole="false" UseCredSsp="true" RenderingEngine="IE"
                ICAEncryptionStrength="EncrBasic" RDPAuthenticationLevel="NoAuth"
                RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false" LoadBalanceInfo=""
                Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
                DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
                EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
                RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
                RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false"
                Connected="false" PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp=""
                VNCCompression="CompNone" VNCEncoding="EncHextile" VNCAuthMode="AuthVNC"
                VNCProxyType="ProxyNone" VNCProxyIP="" VNCProxyPort="0" VNCProxyUsername=""
                VNCProxyPassword="" VNCColors="ColNormal" VNCSmartSizeMode="SmartSAspect"
                VNCViewOnly="false" RDGatewayUsageMethod="Never" RDGatewayHostname=""
                RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername="" RDGatewayPassword=""
                RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
                InheritDescription="false" InheritDisplayThemes="false"
                InheritDisplayWallpaper="false" InheritEnableFontSmoothing="false"
                InheritEnableDesktopComposition="false" InheritDomain="true" InheritIcon="false"
                InheritPanel="false" InheritPassword="true" InheritPort="false"
                InheritProtocol="false" InheritPuttySession="false"
                InheritRedirectDiskDrives="false" InheritRedirectKeys="false"
                InheritRedirectPorts="false" InheritRedirectPrinters="false"
                InheritRedirectSmartCards="false" InheritRedirectSound="false"
                InheritSoundQuality="false" InheritResolution="false" InheritAutomaticResize="false"
                InheritUseConsoleSession="false" InheritUseCredSsp="false"
                InheritRenderingEngine="false" InheritUsername="true"
                InheritICAEncryptionStrength="false" InheritRDPAuthenticationLevel="false"
                InheritRDPMinutesToIdleTimeout="false" InheritRDPAlertIdleTimeout="false"
                InheritLoadBalanceInfo="false" InheritPreExtApp="false" InheritPostExtApp="false"
                InheritMacAddress="false" InheritUserField="false" InheritExtApp="false"
                InheritVNCCompression="false" InheritVNCEncoding="false" InheritVNCAuthMode="false"
                InheritVNCProxyType="false" InheritVNCProxyIP="false" InheritVNCProxyPort="false"
                InheritVNCProxyUsername="false" InheritVNCProxyPassword="false"
                InheritVNCColors="false" InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
                InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
                InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
                InheritRDGatewayPassword="false" InheritRDGatewayDomain="false" />
        </Node>
        <Node Name="DR" Type="Container" Expanded="true" Descr="" Icon="mRemoteNG" Panel="General"
            Id="efb5a39a-dd98-4466-8fdf-ad9f04c3d98a" Username="" Domain="" Password="" Hostname=""
            Protocol="RDP" PuttySession="Default Settings" Port="3389" ConnectToConsole="false"
            UseCredSsp="true" RenderingEngine="IE" ICAEncryptionStrength="EncrBasic"
            RDPAuthenticationLevel="NoAuth" RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false"
            LoadBalanceInfo="" Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
            DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
            EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
            RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
            RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false" Connected="false"
            PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp=""
            VNCCompression="CompNone" VNCEncoding="EncHextile" VNCAuthMode="AuthVNC"
            VNCProxyType="ProxyNone" VNCProxyIP="" VNCProxyPort="0" VNCProxyUsername=""
            VNCProxyPassword="" VNCColors="ColNormal" VNCSmartSizeMode="SmartSAspect"
            VNCViewOnly="false" RDGatewayUsageMethod="Never" RDGatewayHostname=""
            RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername="" RDGatewayPassword=""
            RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
            InheritDescription="false" InheritDisplayThemes="false" InheritDisplayWallpaper="false"
            InheritEnableFontSmoothing="false" InheritEnableDesktopComposition="false"
            InheritDomain="true" InheritIcon="false" InheritPanel="false" InheritPassword="true"
            InheritPort="false" InheritProtocol="false" InheritPuttySession="false"
            InheritRedirectDiskDrives="false" InheritRedirectKeys="false"
            InheritRedirectPorts="false" InheritRedirectPrinters="false"
            InheritRedirectSmartCards="false" InheritRedirectSound="false"
            InheritSoundQuality="false" InheritResolution="false" InheritAutomaticResize="false"
            InheritUseConsoleSession="false" InheritUseCredSsp="false"
            InheritRenderingEngine="false" InheritUsername="true"
            InheritICAEncryptionStrength="false" InheritRDPAuthenticationLevel="false"
            InheritRDPMinutesToIdleTimeout="false" InheritRDPAlertIdleTimeout="false"
            InheritLoadBalanceInfo="false" InheritPreExtApp="false" InheritPostExtApp="false"
            InheritMacAddress="false" InheritUserField="false" InheritExtApp="false"
            InheritVNCCompression="false" InheritVNCEncoding="false" InheritVNCAuthMode="false"
            InheritVNCProxyType="false" InheritVNCProxyIP="false" InheritVNCProxyPort="false"
            InheritVNCProxyUsername="false" InheritVNCProxyPassword="false" InheritVNCColors="false"
            InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
            InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
            InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
            InheritRDGatewayPassword="false" InheritRDGatewayDomain="false">
            <Node Name="Domain Controller" Type="Connection" Descr="" Icon="Windows" Panel="General"
                Id="d090eefc-b666-4c86-9314-5f39cb179319" Username="" Domain="" Password=""
                Hostname="${DC51_PUBLIC_IP}" Protocol="RDP" PuttySession="Default Settings"
                Port="3389"
                ConnectToConsole="false" UseCredSsp="true" RenderingEngine="IE"
                ICAEncryptionStrength="EncrBasic" RDPAuthenticationLevel="NoAuth"
                RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false" LoadBalanceInfo=""
                Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
                DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
                EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
                RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
                RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false"
                Connected="false" PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp=""
                VNCCompression="CompNone" VNCEncoding="EncHextile" VNCAuthMode="AuthVNC"
                VNCProxyType="ProxyNone" VNCProxyIP="" VNCProxyPort="0" VNCProxyUsername=""
                VNCProxyPassword="" VNCColors="ColNormal" VNCSmartSizeMode="SmartSAspect"
                VNCViewOnly="false" RDGatewayUsageMethod="Never" RDGatewayHostname=""
                RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername="" RDGatewayPassword=""
                RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
                InheritDescription="false" InheritDisplayThemes="false"
                InheritDisplayWallpaper="false" InheritEnableFontSmoothing="false"
                InheritEnableDesktopComposition="false" InheritDomain="true" InheritIcon="false"
                InheritPanel="false" InheritPassword="true" InheritPort="false"
                InheritProtocol="false" InheritPuttySession="false"
                InheritRedirectDiskDrives="false" InheritRedirectKeys="false"
                InheritRedirectPorts="false" InheritRedirectPrinters="false"
                InheritRedirectSmartCards="false" InheritRedirectSound="false"
                InheritSoundQuality="false" InheritResolution="false" InheritAutomaticResize="false"
                InheritUseConsoleSession="false" InheritUseCredSsp="false"
                InheritRenderingEngine="false" InheritUsername="true"
                InheritICAEncryptionStrength="false" InheritRDPAuthenticationLevel="false"
                InheritRDPMinutesToIdleTimeout="false" InheritRDPAlertIdleTimeout="false"
                InheritLoadBalanceInfo="false" InheritPreExtApp="false" InheritPostExtApp="false"
                InheritMacAddress="false" InheritUserField="false" InheritExtApp="false"
                InheritVNCCompression="false" InheritVNCEncoding="false" InheritVNCAuthMode="false"
                InheritVNCProxyType="false" InheritVNCProxyIP="false" InheritVNCProxyPort="false"
                InheritVNCProxyUsername="false" InheritVNCProxyPassword="false"
                InheritVNCColors="false" InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
                InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
                InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
                InheritRDGatewayPassword="false" InheritRDGatewayDomain="false" />
            <Node Name="Cloud Connector" Type="Connection" Descr="" Icon="Windows" Panel="General"
                Id="6837bdf6-53a3-41f7-b8e1-c60751a5f747" Username="" Domain="" Password=""
                Hostname="${CC51_PUBLIC_IP}" Protocol="RDP" PuttySession="Default Settings"
                Port="3389"
                ConnectToConsole="false" UseCredSsp="true" RenderingEngine="IE"
                ICAEncryptionStrength="EncrBasic" RDPAuthenticationLevel="NoAuth"
                RDPMinutesToIdleTimeout="0" RDPAlertIdleTimeout="false" LoadBalanceInfo=""
                Colors="Colors16Bit" Resolution="FitToWindow" AutomaticResize="true"
                DisplayWallpaper="false" DisplayThemes="false" EnableFontSmoothing="false"
                EnableDesktopComposition="false" CacheBitmaps="false" RedirectDiskDrives="false"
                RedirectPorts="false" RedirectPrinters="false" RedirectSmartCards="false"
                RedirectSound="DoNotPlay" SoundQuality="Dynamic" RedirectKeys="false"
                Connected="false" PreExtApp="" PostExtApp="" MacAddress="" UserField="" ExtApp=""
                VNCCompression="CompNone" VNCEncoding="EncHextile" VNCAuthMode="AuthVNC"
                VNCProxyType="ProxyNone" VNCProxyIP="" VNCProxyPort="0" VNCProxyUsername=""
                VNCProxyPassword="" VNCColors="ColNormal" VNCSmartSizeMode="SmartSAspect"
                VNCViewOnly="false" RDGatewayUsageMethod="Never" RDGatewayHostname=""
                RDGatewayUseConnectionCredentials="Yes" RDGatewayUsername="" RDGatewayPassword=""
                RDGatewayDomain="" InheritCacheBitmaps="false" InheritColors="false"
                InheritDescription="false" InheritDisplayThemes="false"
                InheritDisplayWallpaper="false" InheritEnableFontSmoothing="false"
                InheritEnableDesktopComposition="false" InheritDomain="true" InheritIcon="false"
                InheritPanel="false" InheritPassword="true" InheritPort="false"
                InheritProtocol="false" InheritPuttySession="false"
                InheritRedirectDiskDrives="false" InheritRedirectKeys="false"
                InheritRedirectPorts="false" InheritRedirectPrinters="false"
                InheritRedirectSmartCards="false" InheritRedirectSound="false"
                InheritSoundQuality="false" InheritResolution="false" InheritAutomaticResize="false"
                InheritUseConsoleSession="false" InheritUseCredSsp="false"
                InheritRenderingEngine="false" InheritUsername="true"
                InheritICAEncryptionStrength="false" InheritRDPAuthenticationLevel="false"
                InheritRDPMinutesToIdleTimeout="false" InheritRDPAlertIdleTimeout="false"
                InheritLoadBalanceInfo="false" InheritPreExtApp="false" InheritPostExtApp="false"
                InheritMacAddress="false" InheritUserField="false" InheritExtApp="false"
                InheritVNCCompression="false" InheritVNCEncoding="false" InheritVNCAuthMode="false"
                InheritVNCProxyType="false" InheritVNCProxyIP="false" InheritVNCProxyPort="false"
                InheritVNCProxyUsername="false" InheritVNCProxyPassword="false"
                InheritVNCColors="false" InheritVNCSmartSizeMode="false" InheritVNCViewOnly="false"
                InheritRDGatewayUsageMethod="false" InheritRDGatewayHostname="false"
                InheritRDGatewayUseConnectionCredentials="false" InheritRDGatewayUsername="false"
                InheritRDGatewayPassword="false" InheritRDGatewayDomain="false" />
        </Node>
    </Node>
</mrng:Connections>