MAIN_AWS_ACCESS_KEY_ID     = "AKIAIOSFODNN7EXAMPLE"
MAIN_AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

DR_AWS_ACCESS_KEY_ID     = "AKIAIOSFODNN7EXAMPLE"
DR_AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

CITRIX_CUSTOMER_ID   = "mock203e4b3"
CITRIX_CLIENT_ID     = "abcd1234-efgh-5678-ijkl-9012mnop3456"
CITRIX_CLIENT_SECRET = "Xyz12l0UxYzXYz-abcDEFw=="

DOMAIN_NAME         = "homelab.corp"
DOMAIN_NETBIOS_NAME = "HL"

ADMINISTRATOR_USERNAME = "Administrator"
ADMINISTRATOR_PASSWORD = "Dummyp@ssw0rd!"

HOSTNAMES = {
  "MAIN_DC" = "DCPD01",
  "MAIN_CC" = "CCPD01",
  "MAIN_GI" = "GIPD01",
  "DR_DC"   = "DCPD51",
  "DR_CC"   = "CCPD51"
}

INGRESS_WITH_CIDR_BLOCKS = [
  {
    cidr_blocks = "XXX.XXX.XXX.XXX/32"
    rule        = "all-all"
  }
]
